### ISSUE TITLE
Tooling: Formatierung Reihenfolge Methoden

### ISSUE THREAD

**Issue by cagix** [Programmiermethoden/Dungeon#1347]
Spotless formatiert nach dem Google Style, interessiert sich aber (scheinbar?!) nicht für die Reihenfolge von Attributen und Methoden.

IntelliJ hat zusätzlich Einstellungen, um Methoden einheitlich zu sortieren.

Gibt es evtl. eine Einstellung in Spotless? Gib es ähnliche Tools, die das erledigen würden?

=> Einbauen in Gradle und CI, Umformatieren der Codebasis.

**Comment by tgrothe** [comment]
Eine schnelle Suche hat ergeben... der umgekehrte Weg wäre möglich, Spotless in Intellij zu verwenden (siehe [hier(1)](https://github.com/diffplug/spotless/issues/200) und [hier(2)](https://github.com/ragurney/spotless-intellij-gradle)), aber anscheinend hat das Spotless Gradle Plugin (bislang) kein Option dafür, den Intellij Formatter für Code Re-arrangement zu verwenden. Ich suche noch weiter, ob das ein Plugin kann.

**Comment by tgrothe** [comment]
Bis jetzt noch nix gefunden ...

**Comment by tgrothe** [comment]
@cagix , clang-format könnte das vielleicht. Und spotless kann clang-format starten:

`build.gradle`
```
tasks.register('spotlessApplyClang') {
    dependsOn 'spotlessJavaApply'
    spotless {
        java {
            targetExclude('build/generated-src/**')
            clangFormat('8.0.1').style('LLVM')
        }
    }
}

tasks.register('spotlessCheckClang') {
    dependsOn 'spotlessJavaCheck'
    spotless {
        java {
            targetExclude('build/generated-src/**')
            clangFormat('8.0.1').style('LLVM')
        }
    }
}
```

`github_ci.yml`
```yml
  spotless:
    name: Spotless
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Prepare spotless
        run: apt install clang-format
      - name: Spotless
        run: ./gradlew spotlessJavaCheck spotlessCheckClang
```

clang-format muss vorher installiert sein.

siehe auch https://clang.llvm.org/docs/ClangFormatStyleOptions.html#basedonstyle
