### ISSUE TITLE
[GitHub] JUnit auf verschiedenen OS laufen lassen

### ISSUE THREAD

**Issue by AMatutat** [Programmiermethoden/Dungeon#845]
In #841 ist ein fehlgeschlagener Test aufgetaucht, der jedoch nur auf Windows fehlschlägt. 
Ursache war wohl der unterschiedliche Umgang mit Zeilenumbrüchen (siehe #844).

Die Tatsache, dass eine fehlerhafte Version in den Master gelangt ist, OBWOHL unsere Tests den Fehler sogar abdecken, ist ärgerlich.

Innerhalb unserer Aktion überprüfen wir zwar, ob das Projekt auf jedem System gebaut werden kann, aber die Tests laufen nur auf Ubuntu.

Die Frage ist: Sollen wir die Tests auf allen Betriebssystemen durchführen lassen?
Vorteil: Mehr Sicherheit
Nachteil: Situationen wie diese sind sehr, sehr selten und unsere CI wird dadurch verlangsamt.

Das ding ist, das sowohl @malt-r als auch @cagix , als auch ich nicht auf Windows arbeiten => Fehler werden erst von den SHKs bemerkt.

**Comment by cagix** [comment]
Um das richtig einzuordnen: Der eigentliche Source-Code war okay, aber im Test-Code wurde ein systemabhängiger Zeilentrenner verwendet, was dann beim Ausführen der Tests unter Windows zum Problem wurde, richtig?

Könnte sowas auch im Source-Tree vorkommen oder ist das eher was Test-spezifisches? 

---

Wenn ich mich richtig erinnere, hatten wir früher schon mal nicht nur den Build an sich, sondern auch die Tests auf "Matrix", also auch in Windows. Dann tauchten seltsame zufällige SSH-Probleme (??) mit Windows auf, so dass wir gesagt haben, die Tests nur noch mit Linux zu machen. 

Was spricht für einen Matrix-Test? 
- Obiges Problem könnte abgefangen werden.

Was spricht gegen einen Matrix-Test?
- CI braucht deutlich länger
- Frühere zufällige CI-Probleme mit Windows und den Tests
- Die Abdeckung unserer Tests liegt vermutlich bei 20% oder so und ist damit nicht so wahnsinnig aussagekräftig

--- 

Schnieke wäre, wenn man bei Änderungen an den Tests diese tatsächlich einmal im Matrix-Build laufen lassen würde, ggf. auch manuell getriggert. Aber das kriegt man vermutlich der CI nicht beigebracht, oder?

**Comment by AMatutat** [comment]
> Um das richtig einzuordnen: Der eigentliche Source-Code war okay, aber im Test-Code wurde ein systemabhängiger Zeilentrenner verwendet, was dann beim Ausführen der Tests unter Windows zum Problem wurde, richtig?

Richtig.

> Könnte sowas auch im Source-Tree vorkommen oder ist das eher was Test-spezifisches?

Aus Dungeon perspektive glaube ich das nicht 


> Wenn ich mich richtig erinnere, hatten wir früher schon mal nicht nur den Build an sich, sondern auch die Tests auf "Matrix", also auch in Windows. Dann tauchten seltsame zufällige SSH-Probleme (??) mit Windows auf, so dass wir gesagt haben, die Tests nur noch mit Linux zu machen.

hab dazu nix gefunden, wir haben https://github.com/Programmiermethoden/Dungeon/pull/206 hier darüber diskutiert und uns aus Laufzeitgründen für eine Test-System geeinigt. 

Vielleicht meintest du https://github.com/Programmiermethoden/Dungeon/issues/728 , das hatte aber nichts mit den Tests sondern mit der Graddle-Wrapper Verifizierung zu tun. 


> Schnieke wäre, wenn man bei Änderungen an den Tests diese tatsächlich einmal im Matrix-Build laufen lassen würde, ggf. auch manuell getriggert. Aber das kriegt man vermutlich der CI nicht beigebracht, oder?

Da müsste ich mich erstmal einbuddeln .
Auf die schnelle scheint das aber tatsächlich zu gehen
https://stackoverflow.com/questions/63822219/how-to-run-github-actions-workflow-only-if-the-pushed-files-are-in-a-specific-fo

**Comment by AMatutat** [comment]
Mal stümperhaft zusammengeklöppelt: 

```
jobs:
  check:
    name: Check files
    outputs:
      run_job: ${{ steps.check_files.outputs.run_job }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  - name: check modified files
    id: check_files
    run: |
      git diff --name-only HEAD^ HEAD &gt; files.txt
      while IFS= read -r file
      do
        echo $file
        if [[ $file == */test/* ]]; then
          echo "::set-output name=run_job::true"
          break
        fi
      done &lt; files.txt

    

junit_test_changed:
name: JUnit if test changed
needs: build , check
if: needs.check.outputs.run_job == 'true'
strategy:
            matrix:
                os: [ ubuntu-latest, windows-latest, macos-latest ]
        runs-on: ${{ matrix.os }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    cache: gradle
            -   name: JUnit
                run: ./gradlew test


junit:
name: JUnit if test not changed
needs: build , check
if: needs.check.outputs.run_job == 'false'
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    cache: gradle
            -   name: JUnit
                run: ./gradlew test
```

Mit richtiger Syntax sollte das jetzt die Tests nur auf Ubunut ausführen, wenn an den Tests keine Änderungen gemacht wurden, ansonsten würde ein Matrix-Build Laufen.
